### PR TITLE
Commands to show pokemon sprites

### PR DESCRIPTION
**Pull request by palt0**
I could transform `generate_sprite_url` to a coroutine and incorporate the `try...except` block in it, but keeping the function synchronous means having simpler unit tests in the future. It also seemed clearer to have different error messages, considering the exception is most likely generated for different reasons.

### CODE REVIEW

**Comment by Parnassius** [comment]
Nice, thank you. However it breaks on `.sprite nidoran-m`, since it looks for a file named `nidoran-m.gif`, while the correct one is `nidoranm.gif`. I think it's because they are two different species, and not a gender difference (they seem to use dashes only if it's a different form of the same pokemon).
I'm not sure how we should approach this, we could require the form name as a different parameter (eg `.sprite oricorio, pompom`). Doing this we could simply remove every non-alphanumeric character from both parameters and concatenate them. The only exceptions seems to be `pikachu-starter-f`, a couple of totems and non-strawberry alcremie. Of those only pikachu is used on PS (totems simply use the base sprite, and you can't change the sweet on alcremie), so I'd probably ignore it.

**Comment by palt0** [comment]
Separating forms with a comma would just make the command more confusing imo. People are accustomed to using a single string separated by `-` from PS and this would stray further away from it. We could honestly just hardcode aliases for nidoran to match PS' convention if it's the only counterintuitive example.

Honestly there's a lot of room for improvements on pokemon name recognition. For example pokemon ending with `-a` and `-alola` are equivalent, etc. but I don't think it's a pressing issue.

**Comment by palt0** [comment]
I could even keep track of suggestions of this kind in an issue and implement them (with tests) after we've collected a good amount.

**Comment by palt0** [comment]
> I think it's because they are two different species, and not a gender difference (they seem to use dashes only if it's a different form of the same pokemon).

Correct.
There real issue isn't really `nidoran-*`, as it is a lone offender and we could hardcode it as an exception, but rather the various suffixes that contain hyphens: `mega-x` should be converted to `megax`, `galar-zen` to `galarzen`, etc.

I think your logic makes sense but I'd rather divide the base name from the form suffix automatically without forcing the end user to do it for us, if possible. Separating forms with a comma would just make the command more confusing: people are accustomed to using a single string separated by hyphens and this change would stray further away from it.

We only really need to determine the point of separation between the base name and the form suffix. It is generally the first occurence a hyphen character, but there are two issues:
1. Base names that also contain hyphens obviously would shift the separation. Are there really many offenders, though? If `nidoran-*` is the only one (or if there are only a few more), we might as well hardcode it as an exception.
2. Some suffixes mantain the hyphen in their sprite URLs. This is just a temporary issue and these files will be renamed to be consistent with the original rule. As you mentioned, most of these Pokemon aren't relevant anyway, so it isn't a pressing issue.

I'll implement this logic, if it makes sense to you, and add tests. I don't really want to overengineer it, though, so we should keep stuff such as aliases (i.e. `marowak-alola` / `marowak-`) out of the discussion. We can eventually implement those in the future after collecting feedback, if we feel they're needed.

**Comment by palt0** [comment]
> I think it's because they are two different species, and not a gender difference (they seem to use dashes only if it's a different form of the same pokemon).

Correct.

The real issue isn't really `nidoran-*`, as it is a lone offender and we could hardcode it as an exception, but rather the various suffixes that contain hyphens: `mega-x` should be converted to `megax`, `galar-zen` to `galarzen`, etc.

I think your logic makes sense but I'd rather divide the base name from the form suffix automatically without forcing the end user to do it for us, if possible. Separating forms with a comma would just make the command more confusing: people are accustomed to using a single string separated by hyphens and this change would stray further away from it.

We only really need to determine the point of separation between the base name and the form suffix. It is generally the first occurence a hyphen character, but there are two issues:
1. Base names that also contain hyphens obviously would shift the separation. Are there really many offenders, though? If `nidoran-*` is the only one (or if there are only a few more), we might as well hardcode it as an exception.
2. Some suffixes mantain the hyphen in their sprite URLs. This is just a temporary issue and these files will be renamed to be consistent with the original rule. As you mentioned, most of these Pokemon aren't relevant anyway, so it isn't a pressing issue.

I'll implement this logic, if it makes sense to you, and add tests. I don't really want to overengineer it, though, so we should keep stuff such as aliases (i.e. `marowak-alola` / `marowak-`) out of the discussion. We can eventually implement those in the future after collecting feedback, if we feel they're needed.

**Comment by palt0** [comment]
> I think it's because they are two different species, and not a gender difference (they seem to use dashes only if it's a different form of the same pokemon).

Correct.

The main issue isn't really `nidoran-*`, as it is a lone offender and we could hardcode it as an exception, but rather the various suffixes that contain hyphens: `mega-x` should be converted to `megax`, `galar-zen` to `galarzen`, etc.

I think your logic makes sense but I'd rather divide the base name from the form suffix automatically without forcing the end user to do it for us, if possible. Separating forms with a comma would just make the command more confusing: people are accustomed to using a single string separated by hyphens and this change would stray away from it.

We only really need to determine the point of separation between the base name and the form suffix. It is generally the first occurence a hyphen character, but there are two issues:
1. Base names that also contain hyphens would obviously shift the separation. Are there really many offenders, though? If `nidoran-*` is the only one (or if there are only a few more), we might as well hardcode it as an exception.
2. Some suffixes mantain the hyphen in their sprite URLs. This is just a temporary issue and these files will be renamed to be consistent with the original rule. As you mentioned, most of these Pokemon aren't relevant anyway, so it isn't a pressing issue.

I'll implement this logic, if it makes sense to you, and add tests. I don't really want to overengineer it though, so we should keep stuff such as aliases (i.e. `marowak-alola` / `marowak-a`) out of the discussion. We can eventually implement those in the future after collecting feedback, if we feel they're needed.

**Comment by palt0** [comment]
> I think it's because they are two different species, and not a gender difference (they seem to use dashes only if it's a different form of the same pokemon).

Correct.

`nidoran-*` is a good example, but the real problem are the various suffixes that contain hyphens: `mega-x` should be converted to `megax`, `galar-zen` to `galarzen`, etc.

I think that your logic makes sense but I'd rather divide the base name from the form suffix automatically without forcing the end user to do it for us, if possible. Separating forms with a comma would just make the command more confusing: people are accustomed to using a single string separated by hyphens and this change would stray away from it.

We only really need to determine the point of separation between the base name and the form suffix. It is generally the first occurence a hyphen character, but there are two issues:
1. Base names that also contain hyphens would obviously shift the separation. Are there really many offenders, though? If `nidoran-*` is the only one (or if there are only a few more), we might as well hardcode it as an exception.
2. Some suffixes mantain the hyphen in their sprite URLs. This is just a temporary issue and these files will be renamed to be consistent with the original rule. As you mentioned, most of these Pokemon aren't relevant anyway, so it isn't a pressing issue.

Just let me know if you're ok with this solution.

**Comment by palt0** [comment]
> I think it's because they are two different species, and not a gender difference (they seem to use dashes only if it's a different form of the same pokemon).

Correct.

`nidoran-*` is a good example, but the real problem are the various suffixes that contain hyphens: `mega-x` should be converted to `megax`, `galar-zen` to `galarzen`, etc.

I think that your logic makes sense but I'd rather divide the base name from the form suffix automatically without forcing the end user to do it for us, if possible. Separating forms with a comma would just make the command more confusing: people are accustomed to using a single string separated by hyphens and this change would stray away from it.

We only really need to determine the point of separation between the base name and the form suffix. It is generally the first occurence a hyphen character, but there are two issues:
1. Base names that also contain hyphens would obviously shift the separation. Are there really many offenders, though? If `nidoran-*` is the only one (or if there are only a few more), we might as well hardcode it as an exception.
2. Some suffixes mantain the hyphen in their sprite URLs. This is just a temporary issue and these files will be renamed to be consistent with the original rule. As you mentioned, most of these Pokemon aren't relevant anyway, so it isn't a pressing issue.

Let me know if you're ok with this solution. Here's a possible implementation: https://github.com/parnassius/cerbottana/commit/9e4a059b3b2054a8669722c30c14bbb21238f19d

**Comment by Parnassius** [comment]
> Separating forms with a comma would just make the command more confusing: people are accustomed to using a single string separated by hyphens and this change would stray away from it.

To be honest I'm not so sure requiring a hyphen would be much better, since showdown accepts things like `kyuremblack` and `kyurem black` as well, so it would only shift the requirement from one character to another. I suggested using a comma mainly to simplify the parsing logic. 

> 1. Base names that also contain hyphens would obviously shift the separation. Are there really many offenders, though? If `nidoran-*` is the only one (or if there are only a few more), we might as well hardcode it as an exception.

The other ones are ho-oh, porygon-z, and the kommo-o line

**Comment by palt0** [comment]
> To be honest I'm not so sure requiring a hyphen would be much better, since showdown accepts things like `kyuremblack` and `kyurem black` as well, so it would only shift the requirement from one character to another. I suggested using a comma mainly to simplify the parsing logic.

I find it less intuitive because writing `/dt ninetales, alola` is not an accepted way to write a variation. I don't really want to overengineer this; I'm fine with having an (arguably) intuitive way to get a pokemon form but possible aliases aren't a priority in my opinion. We might as well introduce them over time after having received feedback.
The debate wasn't really about the character to use as a separator but about the fact that we don't need to force end users to separate base forms / suffixes for us.

> The other ones are ho-oh, porygon-z, and the kommo-o line

Ok I think exception are so few that we can indeed hardcode them.

**Comment by palt0** [comment]
> To be honest I'm not so sure requiring a hyphen would be much better, since showdown accepts things like `kyuremblack` and `kyurem black` as well, so it would only shift the requirement from one character to another. I suggested using a comma mainly to simplify the parsing logic.

I find it less intuitive because writing `/dt ninetales, alola` is not an accepted way to write a variation. I don't really want to overengineer this; I'm fine with having an (arguably) intuitive way to get a pokemon form but possible aliases aren't a priority in my opinion.
The debate wasn't really about the character to use as a separator but about the fact that we don't need to force end users to separate base forms / suffixes for us. They don't really need to remember that `ninetales-alola` and `ho-oh` are treated differently. Also with multiple hyphens it could appear a bit confusing: I can foresee someone writing `darmanitan, galar, zen`.

> The other ones are ho-oh, porygon-z, and the kommo-o line

Ok I think exception are so few that we can indeed hardcode them. I'll update the code to account for these, but are you fine with the logic I proposed?

**Comment by Parnassius** [comment]
> I find it less intuitive because writing `/dt ninetales, alola` is not correct.

Ok, that's a valid point

> Ok I think exception are so few that we can indeed hardcode them. I'll update the code to account for these, but are you fine with the logic I proposed?

I'm not really a fan of hardcoded things, but I think in this case it's ok, at least for now. I was thinking about importing a few data files from the pokemon showdown server ([I created a workflow akin to the veekun one in a test repo](https://github.com/Parnassius/test/blob/126c3ea4bc64dbb991e6c23093ff8bd35a188719/.github/workflows/idk.yml)), and doing that could solve this problem, but for now I'm ok with your solution.

**Comment by palt0** [comment]
Yes, if you're willing to add those datafiles this issue becomes trivial because the base species / form suffix separation is coded in `pokedex.ts`.
Can you accept your own PR in that repository so I can clone it and try to implement the optimal strategy? Thanks.

**Comment by palt0** [comment]
Yes, if you're willing to add those datafiles this issue becomes trivial because the base species / form suffix separation is coded in `pokedex.ts`.

**Comment by Parnassius** [comment]
Yes, I think I'll add them in the next couple of days

**Comment by palt0** [comment]
I'll keep the temporary logic in a separate commit then.

**Pull request merged**
